### ISSUE TITLE
Can I use Ssh.connect with for loops? 

### ISSUE THREAD

**Issue by caiquejjx** [steelbrain/node-ssh#255] opened 2020-02-03 20:03 UTC
I want to connect to a few hosts and exec a command on it, is it possible?

**Comment by aimanebk** [comment] 2020-02-11 15:07
Yes you can , try this one 

```
for (let i = 0; i < instances.length; i++) {
                await new Promise(async(resolve, reject) => {
                    ssh.connect({
                        host: instances[i].IP,
                        username: 'root',
                        port: 22,
                        password : password'
                    })
                    .then(async function() {     
                            command = `ls`;
                            ssh.execCommand(` ${command} `, { cwd:'/' })
                            .then(function(result) {
                                console.log(result)
                            }).catch((err) => {
                                reject('An error has occured while private ips configurations')
                            })
                        
                 
                    })
}
```

**Comment by findo1** [comment] 2020-04-02 10:43
@aimanebk 
Hello, this code doesn't work for me. 
Its says "SyntaxError: await is only valid in async function" and there is an error at the bracket.

Can you post an other example? :)

**Comment by steelbrain** [comment] 2020-04-02 10:44
@findo1 What version of NodeJS are you running? If it’s too old, you may need to transpile with babel

**Comment by findo1** [comment] 2020-04-02 11:45
@steelbrain I'm using Node v12.16.1.

This is my actual Code:

`node_ssh = require('node-ssh')
ssh = new node_ssh()

const verteiler = ["domain1","domain2"]

for(var i = 0; i < verteiler.length; i++){

   ssh.connect({
        host: verteiler[i],
        username: '****',
        port: 22,
        password: '****',
        tryKeyboard: true,
        
        onKeyboardInteractive: (name, instructions, instructionsLang, prompts, finish) => {
            if (prompts.length > 0 && prompts[0].prompt.toLowerCase().includes('password')) {
              finish([password])
            }
        }
    })
    .then(function() {

            ssh.execCommand('whoami', { cwd:'' }).then(function(result) {
                var result = result.stdout.split(' ')
                console.log(result[result.length-1])
                ssh.dispose()


            })

    })
}`

**Comment by steelbrain** [comment] 2020-05-04 03:33
If you want to use ssh connections in loop, make sure to use something like `p-map` with a concurrency set to 1, otherwise create a new client for each connection. Calling `.connect()` on same client without disconnecting may cause weird behavior

**Comment by steelbrain** [comment] 2020-08-03 13:59
Closing because this is an old discussion, not a bug

**Closed by steelbrain** 2020-08-03 13:59 UTC
