### ISSUE TITLE
All configured authentication methods failed

### ISSUE THREAD

**Issue by ChangedenCZD** [steelbrain/node-ssh#98] opened 2017-11-12 08:22 UTC
Env:Windows 10,Node 8.9.1,Npm 5.2.0.
(node:12768) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: All configured authentication methods failed
(node:12768) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by steelbrain** [comment] 2017-11-12 15:48
`All configured authentication methods failed` is the common ssh server error message if your password or provided private key is incorrect. You need to pass the correct password or private key, also make sure that other server-sided checks such as IP/user are correct as well.

Closing as not a bug but feel free to continue discussing

**Closed by steelbrain** 2017-11-12 15:48 UTC

**Comment by ChangedenCZD** [comment] 2017-11-13 10:43
This method is used to solve the problem:
connect.on('ready', function () {});
connect.connect({});

The problem is with the example:
connect.on('ready', function() {}).connect({});

**Comment by steelbrain** [comment] 2017-11-13 15:01
I have no idea where you are using that API since we only ever allow promise 😅  but glad you figured it out

**Comment by ChangedenCZD** [comment] 2017-11-17 04:25
Thx.
