### ISSUE TITLE
PutDirectory cannot create directories remotely

### ISSUE THREAD

**Issue by LiuCaiHe** [steelbrain/node-ssh#121] opened 2018-08-28 10:56 UTC
If it's an empty directory
Direct error reporting for the first time
But uploading again is no problem

```
(node:4670) UnhandledPromiseRejectionWarning: Error: Failure
    at SFTPStream._transform (/Users/liucaihe/WebServer/Tools/tiny/node_modules/ssh2-streams/lib/sftp.js:410:27)
    at SFTPStream.Transform._read (_stream_transform.js:190:10)
    at SFTPStream._read (/Users/liucaihe/WebServer/Tools/tiny/node_modules/ssh2-streams/lib/sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at SFTPStream.Writable.write (_stream_writable.js:294:11)
    at Channel.ondata (_stream_readable.js:663:20)
    at Channel.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
(node:4670) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4670) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by LiuCaiHe** [comment] 2018-08-28 11:00
Similar to 91

**Comment by steelbrain** [comment] 2020-05-04 03:46
Is this still a bug? Can you please provide any information I could use to reproduce the bug?

**Comment by steelbrain** [comment] 2020-05-11 02:48
During the reimplementation of `putDirectory`, I made sure to fix this, since I haven't gotten any reply from OP in a week, closing for now.

Feel free to continue discussing

**Closed** 2020-05-11 02:49 UTC
Labels: unconfirmed bug
